name: Release API

on:
  push:
    branches:
      - dev
      - staging
      - main
  pull_request:
    branches:
      - dev
      - staging
      - main

jobs:
  changed_files:
    runs-on: ubuntu-latest # windows-latest || macos-latest
    name: Test changed-files
    steps:
      - uses: actions/checkout@v4

      # -----------------------------------------------------------------------------------------------------------
      # Example 1
      # -----------------------------------------------------------------------------------------------------------
      - name: Get changed files
        id: changed-files
        uses: tj-actions/changed-files@ed68ef82c095e0d48ec87eccea555d944a631a4c # v46

      - name: Check if any files were changed
        if: steps.changed-files.outputs.any_changed == 'true' || steps.changed-files.outputs.any_modified == 'true'
        run: |
          for file in ${ALL_CHANGED_FILES}; do
            echo "$file was changed"
          done
